import LegalLayout from './LegalLayout';

/**
 * Not-financial-advice + options-risk disclaimer. The single most important
 * legal surface for a research product that surfaces directional readings.
 */
const Disclaimer = () => (
  <LegalLayout
    title="Disclaimer"
    intro="Slayer Terminal is a research, analytics and educational tool that runs on simulated market data. It is not a broker-dealer, investment adviser, or financial planner, it is not connected to any exchange or market-data vendor, and nothing on this site is personalized investment advice or a recommendation to buy, sell, or hold any security."
    sections={[
      {
        /* First, because it is the fact every other sentence on this page
           depends on, and because the audit found the product had never said it
           anywhere. "Delayed or incomplete" — the language this page used to
           lead with on the subject — describes a real feed that is behind. It
           does not describe a feed that does not exist, and a reader who took
           it at face value would have been misled in the more dangerous
           direction. */
        heading: 'The market data here is simulated',
        body: (
          <>
            <p>
              Every price, quote, greek, level, print and flow reading in this application is generated by a model
              running in your browser. There is no exchange connection, no market-data vendor, and no network request
              for market data of any kind. Ticker symbols and company names are used to make the simulation legible;
              the numbers attached to them are not those companies' market data and never were.
            </p>
            <p>
              This means the readings here can be internally coherent and still describe no real market. Treat the
              terminal as an instrument for learning how these readings are constructed and how they behave — never as
              a source of prices, and never as a basis for an order.
            </p>
          </>
        ),
      },
      {
        heading: 'Not investment advice',
        body: (
          <p>
            All content — including scores, verdicts, "setups," levels, probabilities, and any directional
            language — is provided for informational and educational purposes only. It reflects general analytical
            readings, not advice tailored to your objectives, financial situation, or risk tolerance. You are solely
            responsible for your own decisions.
          </p>
        ),
      },
      {
        heading: 'Options carry substantial risk',
        body: (
          <>
            <p>
              Options and other derivatives are complex instruments and carry a high level of risk. You can lose the
              entire amount of your investment in a short period, and certain strategies can expose you to losses
              exceeding your initial outlay. They are not suitable for every investor.
            </p>
            <p>
              Before trading options, read the disclosure document{' '}
              <span className="text-textPrimary">"Characteristics and Risks of Standardized Options"</span> published
              by the Options Clearing Corporation and provided by your broker.
            </p>
          </>
        ),
      },
      {
        heading: 'No recommendation — do your own research',
        body: (
          <p>
            Any label such as QUALIFIED, WATCH, or FADED is an analytical reading of the inputs the tool measures, not a
            solicitation or recommendation. Always conduct your own due diligence and consult a licensed financial
            professional before acting.
          </p>
        ),
      },
      {
        heading: 'No figure here is a measurement of a real market',
        body: (
          <p>
            Because the data is simulated, every figure on every desk — prices, order-flow readings, dark-pool prints,
            dealer positioning, analytics and scores alike — is illustrative. It must not be relied upon as the basis
            for any trading decision, and we make no representation that any figure corresponds to a real quote, a real
            trade, or a real position in the named security.
          </p>
        ),
      },
      {
        heading: 'No performance guarantee',
        body: (
          <p>
            Past or hypothetical performance is not indicative of future results. No representation is made that any
            account will or is likely to achieve results similar to those shown. Any track-record figures are
            illustrative and do not guarantee future outcomes.
          </p>
        ),
      },
      {
        heading: 'No fiduciary relationship',
        body: (
          <p>
            Your use of Slayer Terminal does not create any advisory, brokerage, or fiduciary relationship between you
            and us. We do not receive, hold, or manage your funds, and we do not execute trades on your behalf.
          </p>
        ),
      },
    ]}
  />
);

export default Disclaimer;
