import { Link } from 'react-router-dom';
import { ChevronRight } from 'lucide-react';
import { Kbd } from './parts';

interface QA {
  q: string;
  a: React.ReactNode;
}

const FAQ: QA[] = [
  {
    q: 'Is this financial advice?',
    a: (
      <>No. Slayer Terminal is a research and educational tool. Nothing here is a recommendation to buy, sell or hold
      any security — see the{' '}
      <Link to="/legal/disclaimer" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Disclaimer</Link> for the full terms.</>
    ),
  },
  {
    /* This question used to be answered "prices, levels and flow update
       continuously while the terminal is open" — true of the animation loop,
       and read by any human being as a claim about a market. The app makes no
       network request for market data at all, and this was the one page that
       invited the opposite conclusion. */
    q: 'Where does the data come from?',
    a: (
      <>It is simulated. Every price, level, greek and print you see is generated by a model running in your browser —
      there is no exchange connection and no market-data vendor. The figures move continuously while the terminal is
      open because the model is running, not because a market is. Ticker symbols are used to make the simulation
      legible; the numbers attached to them are not those companies' market data. The{' '}
      <Link to="/legal/disclaimer" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Disclaimer</Link> states this in full.</>
    ),
  },
  {
    q: 'Do I need an account?',
    a: <>No. There are no accounts yet — every desk works without signing in. If accounts arrive later, they will be optional for the core terminal.</>,
  },
  {
    q: 'Where is my data stored?',
    a: (
      <>Your workspace layout, watchlists, tracker, journal and saved views stay in your browser's local storage on
      your device — nothing is sent to a server. You can wipe it any time from Settings. See the{' '}
      <Link to="/legal/privacy" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Privacy Policy</Link>.</>
    ),
  },
  {
    q: 'Which desk should I start with?',
    a: (
      <><Link to="/pulse" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Pulse</Link> is the cockpit — start there.
      Use <Link to="/compass" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Compass</Link> to find a setup,{' '}
      <Link to="/pinpoint" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Pinpoint</Link> to read the dealer positioning
      behind it, and <Link to="/trace" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Trace</Link> to confirm it on the
      tape.</>
    ),
  },
  {
    q: 'How do I switch tickers quickly?',
    a: (
      <>Use the ticker switcher in the top bar, press <Kbd>]</Kbd> / <Kbd>[</Kbd> to step through the watchlist, or open
      the command palette with <Kbd>⌘</Kbd><Kbd>K</Kbd> and type a symbol. Pulse, Compass, Pinpoint, Prove It
      and Tracker rebuild around it, and so do Trace's Dark pool and Scanner. Stocks surveys the whole
      field rather than one name, and Trace's Live tape and Reconstruction stay on the same prints — the switcher is
      hidden wherever it would not change the page.</>
    ),
  },
  {
    q: 'Can I customize my workspace?',
    a: (
      <>Yes — <Link to="/pulse" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Pulse</Link> is fully arrangeable: drag and
      resize panels, load a view from the <span className="text-textPrimary">Views</span> menu (Scalper / Swing / Macro
      among thirteen), and your layout is remembered in your browser.</>
    ),
  },
  {
    q: 'Does it work on mobile?',
    a: <>The navigation and page layouts are responsive, and the Pulse workspace collapses into a readable vertical stack on a phone. Dense tables and heatmaps scroll inside their own panel. That said, the heavy analytics are built for a wide screen — a desktop is the best experience.</>,
  },
  {
    q: 'Can I track my trades?',
    a: (
      <>Yes — <Link to="/tracker" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Tracker</Link> keeps your setups, their
      status and a journal, all stored locally in your browser. The CSV export lives elsewhere: the exposure ledger
      under{' '}
      <Link to="/pinpoint/levels" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Pinpoint → Levels</Link> writes its
      single-leg drill-down out as CSV.</>
    ),
  },
  {
    q: 'Why do a few panels say “data unavailable”?',
    a: <>Some surfaces need feeds the current build does not carry — full Level-2 depth or tick-by-aggressor prints, for example. Those panels say so honestly rather than showing filler, and will light up when the feed is connected.</>,
  },
  {
    q: 'Is there a keyboard-only way to drive the terminal?',
    a: (
      <>Yes. <Kbd>⌘</Kbd><Kbd>K</Kbd> opens the command palette for pages, tickers and actions; <Kbd>?</Kbd> shows every
      shortcut; <Kbd>[</Kbd> / <Kbd>]</Kbd> change ticker. See the{' '}
      <Link to="/guide/shortcuts" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Shortcuts</Link> tab.</>
    ),
  },
  {
    q: 'How do I get help or send feedback?',
    a: (
      <>Post in <Link to="/community" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">Community</Link> (ideas, feature
      requests, feedback) or email{' '}
      <a href="mailto:info@slayerterminal.com" className="text-textPrimary underline underline-offset-2 decoration-white/40 hover:decoration-white/80">info@slayerterminal.com</a>.</>
    ),
  },
];

const Faq = () => (
  <div className="rounded-lg border border-borderSubtle bg-panel divide-y divide-borderSubtle overflow-hidden">
    {FAQ.map(item => (
      <details key={item.q} className="group open:bg-white/[0.015]">
        <summary className="flex items-center gap-3 px-4 py-3.5 cursor-pointer list-none [&::-webkit-details-marker]:hidden hover:bg-rowHover transition-colors">
          {/* The open row is the one thing on this page with state, so it is
              the one thing that earns the accent. */}
          <ChevronRight className="w-4 h-4 text-textMuted group-open:text-select shrink-0 transition-transform group-open:rotate-90" />
          <span className="text-body font-medium text-textPrimary">{item.q}</span>
        </summary>
        <div className="px-4 pb-4 pl-11 text-data text-textSecondary leading-relaxed">{item.a}</div>
      </details>
    ))}
  </div>
);

export default Faq;
