/*
==================================================
  SLAYER TERMINAL - FEED SOURCE (feedSource.ts)
  WHERE THE NUMBERS ON SCREEN CAME FROM, AS A FACT THE UI CAN READ.

  ---------------------------------------------------------------------------
  WHY THIS EXISTS
  ---------------------------------------------------------------------------
  The app runs on core/simulator.ts. It says so in Terms, in the Disclaimer, in
  the Guide's FAQ and twice in the marketing trailer — and nowhere a working
  trader ever looks. Inside the terminal itself the only always-visible legal
  line is SiteFooter's "For informational purposes only. Not investment
  advice.", which says nothing about the data at all. Someone could use these
  desks for an hour without once being told the tape is generated.

  That gap is not merely a missing disclosure; it is what makes per-number
  honesty labelling impossible. Tagging Trace's session premium as MEASURED
  would assert a measurement, and there is no measurement — there is no network
  request for market data of any kind. A provenance system shipped onto an
  unlabelled simulator would invert the credibility it was built to earn.
  core/scanUniverse.ts already caught this exact trap and wrote it down: "the
  obvious pill text for the deepest tier is 'LIVE' — a claim this desk must
  never make about a simulator."

  So the feed names itself here, and the chrome reads it. One fact, one place.

  ---------------------------------------------------------------------------
  SWAPPING IN A REAL FEED
  ---------------------------------------------------------------------------
  Deliberately shaped like core/mathProvider's registry, because it is the same
  kind of promise and should be kept the same way:

      import { setFeedSource } from './core/feedSource';
      setFeedSource({ kind: 'live', label: 'OPRA', detail: '…' });

  A provider that implements core/marketDataProvider and registers itself here
  changes every honesty surface in the app at once. Until one does,
  `SIMULATED_FEED` is the truth and the chrome states it.

  This module holds no market data and no math. It imports nothing.
==================================================
*/

/**
 * What is behind the numbers.
 *
 * `simulated` — generated in this browser; no exchange, no vendor, no request.
 * `delayed`   — a real feed, behind the market by a stated interval.
 * `live`      — a real feed, real time.
 *
 * `delayed` is not speculative padding: on the entitlements this product is
 * built for, the consolidated equity tape arrives 15 minutes late while the
 * options tape is real time, so a terminal showing both at once will need to
 * say which is which. It exists so that day is a registration, not a redesign.
 */
export type FeedKind = 'simulated' | 'delayed' | 'live';

export interface FeedSource {
  kind: FeedKind;
  /** Two or three characters for the chrome badge. Uppercase. */
  label: string;
  /** One sentence, shown on hover. Says plainly what the reader is looking at. */
  detail: string;
}

/** What ships today, and the only honest answer while the simulator drives. */
export const SIMULATED_FEED: FeedSource = {
  kind: 'simulated',
  label: 'SIM',
  detail:
    'Simulated market data. Every price, quote, greek, level and print is generated by a model running in your browser — there is no exchange connection and no market-data vendor.',
};

let active: FeedSource = SIMULATED_FEED;

/** Register the feed behind the desks. Returns the kind now in force. */
export function setFeedSource(source: FeedSource): FeedKind {
  active = source;
  return active.kind;
}

/** Restore the shipped simulator declaration. Used by tests to isolate. */
export function resetFeedSource(): void {
  active = SIMULATED_FEED;
}

/** What is driving the desks right now. */
export function feedSource(): FeedSource {
  return active;
}

/**
 * True while nothing on screen is a measurement of a real market.
 *
 * The gate for any UI that would otherwise claim one. A number cannot be
 * labelled observed, measured or live while this is true, however it was
 * computed — the computation is not the question, the input is.
 */
export function isSimulatedFeed(): boolean {
  return active.kind === 'simulated';
}
