import { carrySource } from '../core/carry';

/*
==================================================
  SLAYER TERMINAL - PROVENANCE (data/provenance.ts)

  What each number on screen is standing on — P-1's
  chip, built before the swap it belongs to.
==================================================

  THE DIRECTIVE PUTS THIS AT SWAP TIME: when the exposure feed lands, a
  ticker it does not cover falls back to the computed chain, and the reader
  should see which one they are looking at. That argument does not start at
  the swap — it is just as true now, when the answer is "all of it is
  modelled", and saying so is the difference between a terminal that is
  honest about its stage and one that looks like it is quoting a feed.

  So the registry exists first, with every family reporting the truth today,
  and `setProvenance` is the one call the swap makes. The chip's rendering
  does not change; only what it says.

  THREE STATES, and the third is why this is not a boolean:

    measured   a feed supplied this number as-is
    derived    computed HERE from something measured — real inputs, our
               arithmetic. A GEX built from a measured chain is derived,
               not measured, and a reader deciding whether to trust the
               dealer sign convention needs that distinction
    modelled   the simulator produced it; no market was consulted

  A surface that mixes families reports the WEAKEST of them, because a panel
  is only as sourced as its least-sourced input. That rule lives in
  `weakest` rather than in each caller, so no two surfaces can disagree
  about what their mixture is.
*/

export type ProvenanceKind = 'measured' | 'derived' | 'modelled';

export interface ProvenanceEntry {
  kind: ProvenanceKind;
  /** One line, shown on hover — what it is standing on, in words. */
  note: string;
}

/** The data families a surface can be built from. */
export type ProvenanceKey = 'chain' | 'exposure' | 'tape' | 'prints' | 'candles' | 'carry' | 'earnings' | 'macro';

const DEFAULTS: Record<ProvenanceKey, ProvenanceEntry> = {
  chain: { kind: 'modelled', note: 'Option chain from the simulator — no options feed on this account yet' },
  exposure: { kind: 'modelled', note: 'GEX/DEX/VEX computed from the modelled chain, with a modelled expiry weighting' },
  tape: { kind: 'modelled', note: 'Price bars walked by the simulator through its own book' },
  prints: { kind: 'modelled', note: 'Option prints generated by the simulator' },
  candles: { kind: 'modelled', note: 'OHLC bars from the simulator' },
  carry: { kind: 'modelled', note: 'Rate and dividend yield are documented assumptions — see core/carry.ts' },
  earnings: { kind: 'modelled', note: 'Earnings dates and implied moves from the earnings engine' },
  macro: { kind: 'derived', note: 'FOMC from the published 2026 calendar; NFP by the first-Friday rule; CPI approximated' },
};

const current: Record<ProvenanceKey, ProvenanceEntry> = { ...DEFAULTS };

/** Weakest-link ordering: a mixture is only as sourced as its worst part. */
const RANK: Record<ProvenanceKind, number> = { measured: 2, derived: 1, modelled: 0 };

export function getProvenance(key: ProvenanceKey): ProvenanceEntry {
  /* The carry family answers from the seam itself rather than from a copy —
     one truth, and a feed that sets the carry cannot leave this stale. */
  if (key === 'carry') {
    const src = carrySource();
    return { kind: src.kind === 'feed' ? 'measured' : 'modelled', note: src.note };
  }
  return current[key];
}

/** The swap's one call. Returns false on an unknown family. */
export function setProvenance(key: ProvenanceKey, entry: ProvenanceEntry): boolean {
  if (!(key in current)) return false;
  current[key] = entry;
  return true;
}

export function resetProvenance(): void {
  for (const k of Object.keys(DEFAULTS) as ProvenanceKey[]) current[k] = DEFAULTS[k];
}

/**
 * What a surface built from several families should report.
 *
 * Empty input is `modelled` rather than `measured`: a panel that names no
 * sources has not proved it has any.
 */
export function weakest(keys: readonly ProvenanceKey[]): ProvenanceEntry {
  if (keys.length === 0) return { kind: 'modelled', note: 'No source declared' };
  let worst = getProvenance(keys[0]);
  for (const k of keys.slice(1)) {
    const e = getProvenance(k);
    if (RANK[e.kind] < RANK[worst.kind]) worst = e;
  }
  return worst;
}

export const PROVENANCE_WORDS: Record<ProvenanceKind, string> = {
  measured: 'measured',
  derived: 'derived',
  modelled: 'modelled',
};
