import { carrySource } from '../core/carry';

/*
==================================================
  SLAYER TERMINAL - PROVENANCE (data/provenance.ts)

  What each number on screen is standing on — P-1's
  chip, built before the swap it belongs to.
==================================================

  THE DIRECTIVE PUTS THIS AT SWAP TIME: when the exposure feed lands, a
  ticker it does not cover falls back to the computed chain, and the reader
  should see which one they are looking at. That argument does not start at
  the swap — it is just as true now, when the answer is "all of it is
  modelled", and saying so is the difference between a terminal that is
  honest about its stage and one that looks like it is quoting a feed.

  So the registry exists first, with every family reporting the truth today,
  and `setProvenance` is the one call the swap makes. The chip's rendering
  does not change; only what it says.

  FIVE KINDS, ordered by one question: how much is this a fact about the
  market right now?

    live        a stream is updating it as you watch — it IS the market
    measured    a feed supplied it as-is; true as of the fetch
    derived     computed HERE from measured inputs — real numbers, our
                arithmetic. A GEX built from a measured chain is derived,
                not measured, and a reader deciding whether to trust the
                dealer sign convention needs that distinction
    model       OUR judgment, however well sourced — the PLAY/FADE/SKIP
                verdict, a conviction score, the news outcome read. No
                vendor supplies these and none can be checked against a
                quote; they are opinions with arithmetic behind them
    simulated   the simulator produced it; no market was consulted

  `model` and `simulated` were one word before, and conflating them hid the
  most important distinction on the desk. A simulated number becomes real
  when a feed lands. A MODELLED one never does — it stays our opinion no
  matter how good the data underneath it gets, and it is the one a paying
  reader most deserves to have flagged.

  AND A SECOND, ORTHOGONAL AXIS: what state is it in.

    ok           current and complete
    stale        the source has one, but this is older than it should be
    partial      some of it arrived, some did not
    unavailable  there is no value at all

  Orthogonal because a MEASURED number can be stale and a LIVE one can be
  partial. Folding state into kind would force a reader to learn a matrix of
  nine words instead of five plus four, and would make "measured but two
  minutes old" unsayable.

  A surface that mixes families reports the WEAKEST of them, because a panel
  is only as sourced as its least-sourced input. That rule lives in
  `weakest` rather than in each caller, so no two surfaces can disagree
  about what their mixture is.
*/

export type ProvenanceKind = 'live' | 'measured' | 'derived' | 'model' | 'simulated';

/**
 * How a value is doing right now — orthogonal to where it came from.
 * Rendered as a modifier on the chip, never as a sixth kind.
 */
export type DataState = 'ok' | 'stale' | 'partial' | 'unavailable';

export const DATA_STATE_WORDS: Record<DataState, string> = {
  ok: '',
  stale: 'stale',
  partial: 'partial',
  unavailable: 'no data',
};

export const DATA_STATE_NOTES: Record<DataState, string> = {
  ok: '',
  stale: 'This has not refreshed as recently as it should have — read it as a last-known value, not a current one.',
  partial: 'Some of what this panel asked for arrived and some did not. What is drawn is real; it is not the whole picture.',
  unavailable: 'There is no value for this right now. Nothing is being estimated in its place.',
};

export interface ProvenanceEntry {
  kind: ProvenanceKind;
  /** One line, shown on hover — what it is standing on, in words. */
  note: string;
}

/** The data families a surface can be built from. */
export type ProvenanceKey = 'chain' | 'exposure' | 'tape' | 'prints' | 'candles' | 'carry' | 'earnings' | 'macro';

const DEFAULTS: Record<ProvenanceKey, ProvenanceEntry> = {
  chain: { kind: 'simulated', note: 'Option chain from the simulator — no options feed on this account yet' },
  exposure: { kind: 'simulated', note: 'GEX/DEX/VEX computed from the modelled chain, with a modelled expiry weighting' },
  tape: { kind: 'simulated', note: 'Price bars walked by the simulator through its own book' },
  prints: { kind: 'simulated', note: 'Option prints generated by the simulator' },
  candles: { kind: 'simulated', note: 'OHLC bars from the simulator' },
  carry: { kind: 'simulated', note: 'Rate and dividend yield are documented assumptions — see core/carry.ts' },
  earnings: { kind: 'simulated', note: 'Earnings dates and implied moves from the earnings engine' },
  macro: { kind: 'derived', note: 'FOMC from the published 2026 calendar; NFP by the first-Friday rule; CPI approximated' },
};

const current: Record<ProvenanceKey, ProvenanceEntry> = { ...DEFAULTS };

/** Weakest-link ordering: a mixture is only as sourced as its worst part. */
const RANK: Record<ProvenanceKind, number> = { live: 4, measured: 3, derived: 2, model: 1, simulated: 0 };

export function getProvenance(key: ProvenanceKey): ProvenanceEntry {
  /* The carry family answers from the seam itself rather than from a copy —
     one truth, and a feed that sets the carry cannot leave this stale. */
  if (key === 'carry') {
    const src = carrySource();
    return { kind: src.kind === 'feed' ? 'measured' : 'simulated', note: src.note };
  }
  return current[key];
}

/** The swap's one call. Returns false on an unknown family. */
export function setProvenance(key: ProvenanceKey, entry: ProvenanceEntry): boolean {
  if (!(key in current)) return false;
  current[key] = entry;
  return true;
}

export function resetProvenance(): void {
  for (const k of Object.keys(DEFAULTS) as ProvenanceKey[]) current[k] = DEFAULTS[k];
}

/**
 * What a surface built from several families should report.
 *
 * Empty input is `modelled` rather than `measured`: a panel that names no
 * sources has not proved it has any.
 */
export function weakest(keys: readonly ProvenanceKey[]): ProvenanceEntry {
  if (keys.length === 0) return { kind: 'simulated', note: 'No source declared' };
  let worst = getProvenance(keys[0]);
  for (const k of keys.slice(1)) {
    const e = getProvenance(k);
    if (RANK[e.kind] < RANK[worst.kind]) worst = e;
  }
  return worst;
}

export const PROVENANCE_WORDS: Record<ProvenanceKind, string> = {
  live: 'live',
  measured: 'measured',
  derived: 'derived',
  model: 'model',
  simulated: 'simulated',
};

/** The sentence behind each word — what the chip says on hover. */
export const PROVENANCE_NOTES: Record<ProvenanceKind, string> = {
  live: 'A stream is updating this as you watch.',
  measured: 'A data feed supplied this value as-is.',
  derived: 'Computed here from measured inputs — real numbers, our arithmetic.',
  model: 'Our own model produced this. It is a judgment, not a quote, and no feed can confirm it.',
  simulated: 'The simulator produced this. No market was consulted.',
};
